browser = "chrome"
btn_contact = "css:a[href=\"#/contact\"]"
btn_shop = "css:a[href=\"#/shop\"]"
btn_cart = "css:a[href=\"#/cart\"]"
input_forename = "css:input#forename"
input_surname = "css:input#surname"
input_email = "css:input#email"
input_telephone = "css:input#telephone"
input_message = "css:textarea#message"
btn_submit = "css:a.btn-contact"
contact_success_msg = "css:div.alert"
modal_feedback = "css:div.popup"
cart_ctr = "css:span.cart-count"
btn_frog_buy = "xpath://li[@id='product-2']//a[@class='btn btn-success']"
btn_bunny_buy = "xpath://li[@id='product-4']//a[@class='btn btn-success']"
btn_vbear_buy = "xpath://li[@id='product-7']//a[@class='btn btn-success']"
btn_checkout = "css:a.btn-checkout"
btn_empty_cart = "css:ng-confirm[title='Empty Cart']"
url_jupiter = "https://jupiter.cloud.planittesting.com/#"
url_contact = "https://jupiter.cloud.planittesting.com/#/contact"
url_shop = "https://jupiter.cloud.planittesting.com/#/shop"
url_cart = "https://jupiter.cloud.planittesting.com/#/cart"
lbl_frog_price = "xpath://li[@id='product-2']//p//span"
lbl_bunny_price = "xpath://li[@id='product-4']//p//span"
lbl_vbear_price = "xpath://li[@id='product-7']//p//span"
cart_lbl_frog_price = "css:.table tr:nth-child(1) td:nth-child(2)"
cart_lbl_bunny_price = "css:.table tr:nth-child(2) td:nth-child(2)"
cart_lbl_vbear_price = "css:.table tr:nth-child(3) td:nth-child(2)"
cart_lbl_frog_subtotal_price = "css:.table tr:nth-child(1) td:nth-child(4)"
cart_lbl_bunny_subtotal_price = "css:.table tr:nth-child(2) td:nth-child(4)"
cart_lbl_vbear_subtotal_price = "css:.table tr:nth-child(3) td:nth-child(4)"
cart_lbl_total_price = "css:.table tfoot tr:nth-child(1) .total"